name: Auto Renew GitHub Token

on:
  schedule:
    - cron: "0 0 */25 * *"  # Runs every 25 days
  workflow_dispatch:  # Allows manual run

jobs:
  renew-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate new token
        run: |
          NEW_TOKEN=$(curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/YOUR_USERNAME/YOUR_REPOSITORY/actions/secrets \
          -d '{"note": "Auto-renewed token for journal access", "scopes": ["repo"]}' | jq -r .token)

          if [[ -z "$NEW_TOKEN" || "$NEW_TOKEN" == "null" ]]; then
            echo "Failed to generate a new token!"
            exit 1
          fi

          echo "::add-mask::$NEW_TOKEN"
          echo "NEW_TOKEN=$NEW_TOKEN" >> $GITHUB_ENV

      - name: Update repository secret
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/YOUR_USERNAME/YOUR_REPOSITORY/actions/secrets/PAT_TOKEN \
          -d '{"encrypted_value": "${{ env.NEW_TOKEN }}"}'
